server: https://chat.service.tokenbrowser.com
token_ethereum_service_url: https://ethereum.service.tokenbrowser.com
token_id_service_url: https://identity.service.tokenbrowser.com
store: store
redis:
    envKey: REDIS_URL
    timeout: 2000
storage:
  envKey: DATABASE_URL